#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/student
#spring.datasource.username=postgres
#spring.datasource.password=
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#
#
#spring.datasource.initialization-mode=always
#spring.datasource.initialize=true
#spring.datasource.schema=classpath:/schema.sql
#spring.datasource.continue-on-error=true

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/sahelcode
    username: sahelcode  # Use 'username' instead of 'user'
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true

      